TodoApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls")),
]

urlpatterns += staticfiles_urlpatterns()

todo/urls.py
from django.urls import path
from . import views as v

app_name = "todo"
urlpatterns = [
    path('', v.IndexView.as_view(), name="index"),
    path('signup/', v.signup, name="signup"),
    path('login/',v.login,name="login"),
    path('todoIndex/',v.todoIndex,name="todo-index"),
    path('addTask/',v.addtask,name="todo-add"),
    path('editTask/<int:task_id>',v.edittask, name="todo-edit"),
    path('deleteTask/<int:task_id>',v.deletetask,name="todo-delete"),
    path('logout',v.logout,name="logout")
]

todo/models.py
from django.db import models

# Create your models here.

"""USER TABLE"""
class User(models.Model):
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, null=False)
    tel = models.CharField(max_length=15)
    pwd = models.CharField(max_length=100,null=False)

    def __str__(self):
        return self.lname

"""TASKS TABLE"""
class Task(models.Model):
    user_fk = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, null=False)
    description = models.TextField()
    date = models.DateField("date_published")
    time = models.TimeField("time_published")

    def __str__(self):
        return self.title

todo/forms.py
from django import forms

from .models import User,Task

class SignupForm(forms.ModelForm):
    #Password field
    pwd = forms.CharField(widget=forms.TextInput(attrs={"type":"password"}))

    required_css_class = "required-field"
    error_css_class = "error-field"
    class Meta:
        #Bringing all data
        model = User
        fields = '__all__'

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # self.fields["pwd"].widget.attrs.update({"type": "password"})

        label = ["First name","Last name", "Email", "Phone Number","Password"]
        pholder = ["First name...","Last name...", "Email@gmail.com", "1234567890","Your password"]
        i = 0

        for field in self.fields:
            self.fields[str(field)].widget.attrs.update({"class":"form-control mt-2 mb-2 form-control-md"})
            self.fields[str(field)].label = label[i]
            self.fields[str(field)].widget.attrs.update(placeholder = str(pholder[i]))
            i += 1

class LoginForm(forms.ModelForm):
    pwd = forms.CharField(widget=forms.TextInput(attrs={"type":"password"}))

    required_css_class = "required-field"
    error_css_class = "error-field"
    class Meta:
        #Bring the two data to use
        model = User
        fields = ["email","pwd"]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # self.fields["pwd"].widget.attrs.update({"type":"password"})

        label = ["Email Adress","Password"]
        pholder = ["sombody@mail.com","Your passowrd"]
        i = 0

        for field in self.fields:
            self.fields[str(field)].widget.attrs.update({"class":"form-control mt-2 mb-2 form-control-md"})
            self.fields[str(field)].label = label[i]
            self.fields[str(field)].widget.attrs.update(placeholder=str(pholder[i]))
            i += 1

class AddTaskForm(forms.ModelForm):
    date = forms.DateTimeField(widget=forms.DateInput(attrs={"type":"date"}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={"type":"time"}))

    required_css_class = "required-field"
    error_css_class = "error-field"
    class Meta:
        model = Task
        fields = ["title","description","date","time"]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # self.fields["date"].widget.attrs.update({"type":"date"})
        # self.fields["time"].widget.attrs.update({"type":"time"})
        labels = ["Title", "Description", "Date","Time"]
        i = 0

        for field in self.fields:
            self.fields[str(field)].widget.attrs.update({"class":"form-control mt-2 mb-2 form-control-md"})
            self.fields[str(field)].label = labels[i]
            i += 1

todo/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect

from .forms import SignupForm,LoginForm,AddTaskForm
from .models import User, Task


class IndexView(generic.TemplateView):
    template_name = "todo/index.html"
    
    def get(self,request):
        try:
            set_and_auth = self.request.session["auth"] and self.request.session["user_id"]
        except KeyError:
            self.request.session["auth"] = False 
            self.request.session["user_id"] = -1
            return render(request, "todo/index.html")
        else:
            if set_and_auth:
                return HttpResponseRedirect(reverse("todo:todo-index"))
            else:
                return render(request,"todo/index.html")
            

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        email = request.POST["email"]
        pwd = request.POST["pwd"]

        if form.is_valid():
            if len(pwd) < 8:
                print(len(pwd))
                message = "The length of the password must be 8 or more chars *"
                # form = SignupForm()
                return render(request, "todo/todo_signup.html",{"form":form,"msg":message})
            else:
                print("Form saved successfully")
                form.save()
                user_id = User.objects.get(email=email,pwd=pwd).id
                request.session["auth"] = True
                request.session["user_id"] = user_id
                return HttpResponseRedirect(reverse("todo:todo-index"))
            
         # if form is not valid
        else:
            message = "There's an error while sending the form"
            return render(request, "todo/todo_signup.html",{"form":form,"msg":message})
    else:
        form = SignupForm()
        return render(request, "todo/todo_signup.html",{"form":form})


def login(request):
    msg = ""
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST["email"]
            pwd = request.POST["pwd"]
            form = LoginForm(request.POST)
            t = User.objects.filter(email=email,pwd=pwd).count()
            print(t)

            #Verify if there is a user with the current authentication
            if t > 0:
                user = User.objects.get(email=email,pwd=pwd)
                request.session["auth"] = True
                request.session["user_id"] = user.id
                return HttpResponseRedirect(reverse("todo:todo-index"))
            else:
                msg = "Password or email is not correct !"

        else:
            msg = "There an error while submiting the data"

    form = LoginForm()
    return render(request,"todo/todo_login.html",{"form":form, "msg":msg})


def todoIndex(request):
    
    if request.session["auth"] and request.session["user_id"]:
        user_id = request.session["user_id"]
        tasks = User.objects.get(pk=user_id).task_set.all()
        
        return render(request,"todo/todo_index.html",{"tasks":tasks})
    else: 
        return HttpResponseRedirect(reverse("todo:index"))


def addtask(request):
    if request.session["auth"] and request.session["user_id"]:
                
        addmsg = ""
        if request.method == "POST":
            user = User.objects.get(pk=request.session["user_id"])
            form = AddTaskForm(request.POST)

            if form.is_valid():
                title = form.cleaned_data["title"]
                description = form.cleaned_data["description"]
                date = form.cleaned_data["date"]
                time = form.cleaned_data["time"]

                task = Task.objects.create(title=title,description=description,date=date,time=time,user_fk=user)
                task.save()
                return HttpResponseRedirect(reverse("todo:todo-index"))
        addform = AddTaskForm()
        return render(request,'todo/add.html',{"addform":addform,"addmsg":addmsg})
    
    return HttpResponseRedirect(reverse("todo:index"))
    


def edittask(request, task_id):
    if request.session["auth"] and request.session["user_id"]:
        msg=""
        task = Task.objects.get(pk=task_id)
        
        if request.method == "POST":
            form = AddTaskForm(request.POST, instance=task)
            
            if form.is_valid():
                
                #Form data
                title = form.cleaned_data["title"]
                description = form.cleaned_data["description"]
                date = form.cleaned_data["date"]
                time = form.cleaned_data["time"]

                #Updating data in the task fields
                task.title = title
                task.description = description
                task.date = date
                task.time = time

                task.save()
                return HttpResponseRedirect(reverse("todo:todo-index"))
            else:
                msg = "Error while sending the data"

        editform = AddTaskForm(instance=task)
        return render(request,'todo/update.html',{"editform":editform,"msg":msg,"task":task})

    return HttpResponseRedirect(reverse("todo:index"))


def deletetask(request,task_id):
    task = Task.objects.get(pk=task_id)
    task.delete()
    print("Task deleted successfully")

    return HttpResponseRedirect(reverse('todo:todo-index'))

def logout(request):
    del request.session["auth"]
    del request.session["user_id"]
    request.session["auth"] = False
    return HttpResponseRedirect(reverse("todo:index"))

todo/templates/todo/add.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Add Task{% endblock title %}

{% block content %}
        <!-- Modal Add Form -->
    <div class="">
        <div class="bg-light card mt-4 round" >
            <!-- Header form -->
            <div class="card-header align-items-center d-flex flex-row justify-content-center p-3">
                <h2 class="text-success m-2" style="text-align:center;">Add a new task </h2>
                <div class="icon m-2"><i class="text-success bi bi-journal-check"></i></div>
            </div>

            <!-- Main form body -->

            <form class="card-body" method="post" action="{% url 'todo:todo-add' %}">
                {% csrf_token %}
                {{ addform }}
                <p class="text-danger mt-3 radius">{{ addmsg }}</p>
                <input style="width:100%;" class="justify-content-center mt-3 btn btn-success" type="submit" value="Submit">
            </form>
            <a href="{% url 'todo:todo-index' %}" class="btn btn-danger bg-danger card-footer text-light">Cancel</a>
        </div>
    </div>

{% endblock content %}

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{%  static "todo/vue.css" %}'>
    <link rel="stylesheet" href='{%  static "todo/bts/css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "todo/bootstrap-icons/bootstrap-icons.css" %}'>

    <script src="{% static 'todo/bts/js/bootstrap.min.js' %}" defer></script>
  <style>
    .icon {
      border-radius: .25rem;
    }
    .bi {
      margin: .25rem;
      font-size: 3rem;
    }
  </style>
    <title>{% block title %} {% endblock title %}</title>
</head>
<body class="bg-dark">
<!-- <> -->
    {% block content %} {% endblock content %}
</body>
</html>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Index TODO{% endblock title %}

{% block content %}
       <div class="row">
            <div class="col-sm-8 justify-content-center jumbotron jumbotron-fluid  ">
                <h1 class="m-4 inli text-light p-3 display-1 ">My Todo App</h1>
            </div>
            <nav class="col-sm-4 justify-content-center navbar navbar-expand-sm">
              <!-- Links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link p-2 m-3 btn-success text-light" href="{% url 'todo:signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link p-2 m-3 text-success " href="{% url 'todo:login' %}">Log in</a>
                    </li>
                </ul>
            </nav>
       </div>

    <div class="container down">
        <div class="row">
            <div class="col-md-8">
                <h2 class="text-light display-4">
                    Plan your journey like a <span class="text-success">real "MANAGER"</span>
                </h2>
                <img src="{% static 'todo/images/animation_500_l9vj8ca8.gif' %}" alt="Gif">
            </div>
        </div>
    </div>
{% endblock content %}

todo/templates/todo/todo_index.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Todo App{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 justify-content-center jumbotron jumbotron-fluid  ">
            <h1 class="m-4 inli text-light p-3 display-1 ">My Todo App</h1>
        </div>
        <nav class="col-sm-4 justify-content-center navbar navbar-expand-sm">
        <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link p-2 m-3 btn-success text-light" href="{% url 'todo:logout' %}">Log out</a>
                </li>
            </ul>
        </nav>
    </div>


    <!-- <> -->
    <div class="row">
        <div class="col-lg-6">
            <img alt="Gif image" src="{% static 'todo/images/animation_500_l9vj8mp0.gif' %}" width="100%">
        </div>

        <div class="col-lg-6 bg-light card mt-4 round-index" >
            <!-- Header form -->
            <div class="card-header align-items-center d-flex flex-row justify-content-center p-3">
                <h2 class="text-success m-2" style="text-align:center;">YOUR TASKS </h2>
                <div class="icon m-2"><i class="text-success bi bi-list-task"></i></div>
            </div>
        <!-- Main form body -->
            <div class="card-body ovflow">
            {% for task in tasks %}
                <div class="card mt-4 shad">
                    <div class="card-header bg-success text-light">
                        <h3 class="card-title">{{task.title}}</h3>
                    </div>

                    <div class="car-body">
                        <p class="card-text p-3 text-muted">{{task.description}}</p>
                    </div>

                    <div class="card-footer">
                        <p>{{task.date}} at {{task.time}}</p>
                    </div>

                    <div class="d-flex flex-row justify-content-end">
                        <a class="bg-primary p-2 mleft text-light" href="{% url 'todo:todo-edit' task.id %}">Edit</a>
                        <a class="bg-danger p-2 mleft text-white" href="{% url 'todo:todo-delete' task.id %}">Delete</a>
                    </div>
                </div>
            {% endfor %}
            </div>
            <div class="d-flex justify-content-center">
                <a class="" href="{% url 'todo:todo-add' %}"><div class="cent icon"><i class="text-success display-1 cent bi bi-plus-square-fill"></i></div></a>
            </div>
        </div>
    </div>



{% endblock content %}

todo/templates/todo/todo_login.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Signe up{% endblock title %}

{% block content %}

    <!-- Main form container -->
    <div class="bg-light card mt-4 round" >
        <!-- Header form -->
        <div class="card-header">
            <h2 class="text-success">Log into</h2>
        </div>

        <!-- Main form body -->

        <form class="card-body" method="post" action="{% url 'todo:login' %}">
            {% csrf_token %}
            {{ form }}
            <input style="width:100%;" class="justify-content-center mt-3 btn btn-success" type="submit" value="Submit">
            <p class="alert-danger p-1 mt-3 radius">{{ msg }}</p>
        </form>
        <p class="card-footer text-black">Do not have an account ? <br> <a class="text-success" href="{% url 'todo:signup' %}">Sign up</a>.</p>
        <a class="btn btn-black bg-secondary text-body" href="{% url 'todo:index' %}">Return back to home</a>
    </div>


{% endblock content %}

todo/templates/todo/todo_signup.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Signe up{% endblock title %}

{% block content %}
    <!-- Main form container -->
    <div class="bg-light card mt-4 round" >
        <!-- Header form -->
        <div class="card-header">
            <h2 class="text-success">Sign up</h2>
        </div>

        <!-- Main form body -->

        <form class="card-body" method="post" action="{% url 'todo:signup' %}">
            {% csrf_token %}
            {{ form }}
            <input style="width:100%;" class="justify-content-center mt-3 btn btn-success" type="submit" value="Submit" >
            <p class="text-danger p-2 mt-2">{{ msg }}</p>
        </form>
        <p class="card-footer text-black">Already have an account ? <br> <a class="text-success" href="{% url 'todo:login' %}">Log into</a>.</p>
        <a class="btn btn-black bg-secondary text-body" href="{% url 'todo:index' %}">Return back to home</a>
    </div>


{% endblock content %}

todo/templates/todo/update.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Edit Task{% endblock title %}

{% block content %}
        <!-- Modal Add Form -->
    <div class="">
        <div class="bg-light card mt-4 round" >
            <!-- Header form -->
            <div class="card-header align-items-center d-flex flex-row justify-content-center p-3">
                <h2 class="text-success m-2" style="text-align:center;">Edit the following task </h2>
                <div class="icon m-2"><i class="text-success bi bi-journal-check"></i></div>
            </div>

            <!-- Main form body -->

            <form class="card-body" method="post" action="{% url 'todo:todo-edit' task.id %}">
                {% csrf_token %}
                {{ editform }}
                <p class="text-danger mt-3 radius">{{ msg }}</p>
                <input style="width:100%;" class="justify-content-center mt-3 btn btn-success" type="submit" value="Submit">
            </form>
            <a href="{% url 'todo:todo-index' %}" class="btn btn-danger bg-danger card-footer text-light">Cancel</a>
        </div>
    </div>

{% endblock content %}